# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'setup-lnmp'
description: 'Set up your GitHub Actions workflow with khs1994-docker/lnmp'
author: 'khs1994'
inputs:
  lnmp_branch:
    description: lnmp branch
    default: "23.11"
    required: false
  lnmp_services:
    description: lnmp services
    default: nginx mysql php8 redis
    required: false
  lrew_include:
    description: LREW package
    default: pcit
    required: false
  docker_compose_version:
    description: docker compose version
    default: 1.29.0
    required: false
runs:
  using: 'node12'
  main: 'lib/setup-lnmp.js'
branding:
  icon: 'box'
  color: 'green'
